backend/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  post 'auth_user' => 'authentication#authenticate_user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope :api, defaults: {format: :json} do
    scope :hr do
      get 'dashboard' => 'hr#dashboard'
      post 'create_company_asset' => 'hr#create_company_asset'
      patch 'update_company_asset' => 'hr#update_company_asset'
      delete 'delete_company_asset' => 'hr#delete_company_asset'
    end

    scope :employee do
      get 'dashboard' => 'employee#dashboard'
      post 'request_asset' => 'employee#request_asset'
    end
    get 'info' => 'api#info'
    # resources :user_assets
    # resources :users
    # resources :company_assets
  end
  get "/404" => "error#not_found"
  get "/500" => "error#exception"
end

backend/app/models/user_asset.rb
class UserAsset < ApplicationRecord
  belongs_to :user
end

backend/app/controllers/user_assets_controller.rb
class UserAssetsController < ApplicationController
  before_action :set_user_asset, only: [:show, :edit, :update, :destroy]

  # GET /user_assets
  # GET /user_assets.json
  def index
    @user_assets = UserAsset.all
  end

  # GET /user_assets/1
  # GET /user_assets/1.json
  def show
  end

  # GET /user_assets/new
  def new
    @user_asset = UserAsset.new
  end

  # GET /user_assets/1/edit
  def edit
  end

  # POST /user_assets
  # POST /user_assets.json
  def create
    @user_asset = UserAsset.new(user_asset_params)

    respond_to do |format|
      if @user_asset.save
        format.html { redirect_to @user_asset, notice: 'User asset was successfully created.' }
        format.json { render :show, status: :created, location: @user_asset }
      else
        format.html { render :new }
        format.json { render json: @user_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_assets/1
  # PATCH/PUT /user_assets/1.json
  def update
    respond_to do |format|
      if @user_asset.update(user_asset_params)
        format.html { redirect_to @user_asset, notice: 'User asset was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_asset }
      else
        format.html { render :edit }
        format.json { render json: @user_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_assets/1
  # DELETE /user_assets/1.json
  def destroy
    @user_asset.destroy
    respond_to do |format|
      format.html { redirect_to user_assets_url, notice: 'User asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_asset
      @user_asset = UserAsset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_asset_params
      params.require(:user_asset).permit(:asset_name, :count, :status, :returned, :user_id)
    end
end

backend/app/helpers/user_assets_helper.rb
module UserAssetsHelper
end

backend/app/views/user_assets/_form.html.erb
<%= form_with(model: user_asset, local: true) do |form| %>
  <% if user_asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_asset.errors.count, "error") %> prohibited this user_asset from being saved:</h2>

      <ul>
      <% user_asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :asset_name %>
    <%= form.text_field :asset_name %>
  </div>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :returned %>
    <%= form.number_field :returned %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/user_assets/edit.html.erb
<h1>Editing User Asset</h1>

<%= render 'form', user_asset: @user_asset %>

<%= link_to 'Show', @user_asset %> |
<%= link_to 'Back', user_assets_path %>

backend/app/views/user_assets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Assets</h1>

<table>
  <thead>
    <tr>
      <th>Asset name</th>
      <th>Count</th>
      <th>Status</th>
      <th>Returned</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_assets.each do |user_asset| %>
      <tr>
        <td><%= user_asset.asset_name %></td>
        <td><%= user_asset.count %></td>
        <td><%= user_asset.status %></td>
        <td><%= user_asset.returned %></td>
        <td><%= user_asset.user %></td>
        <td><%= link_to 'Show', user_asset %></td>
        <td><%= link_to 'Edit', edit_user_asset_path(user_asset) %></td>
        <td><%= link_to 'Destroy', user_asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Asset', new_user_asset_path %>

backend/app/views/user_assets/new.html.erb
<h1>New User Asset</h1>

<%= render 'form', user_asset: @user_asset %>

<%= link_to 'Back', user_assets_path %>

backend/app/views/user_assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Asset name:</strong>
  <%= @user_asset.asset_name %>
</p>

<p>
  <strong>Count:</strong>
  <%= @user_asset.count %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user_asset.status %>
</p>

<p>
  <strong>Returned:</strong>
  <%= @user_asset.returned %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_asset.user %>
</p>

<%= link_to 'Edit', edit_user_asset_path(@user_asset) %> |
<%= link_to 'Back', user_assets_path %>