backend/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  post 'auth_user' => 'authentication#authenticate_user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope :api, defaults: {format: :json} do
    scope :hr do
      get 'dashboard' => 'hr#dashboard'
      post 'create_company_asset' => 'hr#create_company_asset'
      patch 'update_company_asset' => 'hr#update_company_asset'
      delete 'delete_company_asset' => 'hr#delete_company_asset'
    end

    scope :employee do
      get 'dashboard' => 'employee#dashboard'
      post 'request_asset' => 'employee#request_asset'
    end
    get 'info' => 'api#info'
    # resources :user_assets
    # resources :users
    # resources :company_assets
  end
  get "/404" => "error#not_found"
  get "/500" => "error#exception"
end

backend/app/models/company_asset.rb
class CompanyAsset < ApplicationRecord

end

backend/app/controllers/company_assets_controller.rb
class CompanyAssetsController < ApplicationController
  before_action :set_company_asset, only: [:show, :edit, :update, :destroy,:create]

  # GET /company_assets
  # GET /company_assets.json
  def index
    @company_assets = CompanyAsset.all
  end

  # GET /company_assets/1
  # GET /company_assets/1.json
  def show
  end

  # GET /company_assets/new
  def new
    @company_asset = CompanyAsset.new
  end

  # GET /company_assets/1/edit
  def edit
  end

  # POST /company_assets
  # POST /company_assets.json
  def create
    @company_asset = CompanyAsset.new(company_asset_params)

    respond_to do |format|
      if @company_asset.save
        format.html { redirect_to @company_asset, notice: 'Company asset was successfully created.' }
        format.json { render :show, status: :created, location: @company_asset }
      else
        format.html { render :new }
        format.json { render json: @company_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company_assets/1
  # PATCH/PUT /company_assets/1.json
  def update
    respond_to do |format|
      if @company_asset.update(company_asset_params)
        format.html { redirect_to @company_asset, notice: 'Company asset was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_asset }
      else
        format.html { render :edit }
        format.json { render json: @company_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_assets/1
  # DELETE /company_assets/1.json
  def destroy
    @company_asset.destroy
    respond_to do |format|
      format.html { redirect_to company_assets_url, notice: 'Company asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_asset
      @company_asset = CompanyAsset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_asset_params
      params.require(:company_asset).permit(:name, :count)
    end
end

backend/app/helpers/company_assets_helper.rb
module CompanyAssetsHelper
end

backend/app/views/company_assets/_form.html.erb
<%= form_with(model: company_asset, local: true) do |form| %>
  <% if company_asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company_asset.errors.count, "error") %> prohibited this company_asset from being saved:</h2>

      <ul>
      <% company_asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/company_assets/edit.html.erb
<h1>Editing Company Asset</h1>

<%= render 'form', company_asset: @company_asset %>

<%= link_to 'Show', @company_asset %> |
<%= link_to 'Back', company_assets_path %>

backend/app/views/company_assets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Company Assets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_assets.each do |company_asset| %>
      <tr>
        <td><%= company_asset.name %></td>
        <td><%= company_asset.count %></td>
        <td><%= link_to 'Show', company_asset %></td>
        <td><%= link_to 'Edit', edit_company_asset_path(company_asset) %></td>
        <td><%= link_to 'Destroy', company_asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company Asset', new_company_asset_path %>

backend/app/views/company_assets/new.html.erb
<h1>New Company Asset</h1>

<%= render 'form', company_asset: @company_asset %>

<%= link_to 'Back', company_assets_path %>

backend/app/views/company_assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company_asset.name %>
</p>

<p>
  <strong>Count:</strong>
  <%= @company_asset.count %>
</p>

<%= link_to 'Edit', edit_company_asset_path(@company_asset) %> |
<%= link_to 'Back', company_assets_path %>